### ISSUE TITLE
[Feature] Add pomodoro timer feature

### ISSUE THREAD

**Issue by replete** [replete/obsidian-day-planner#2]
Someone had a good idea the unmerged/abandoned 'daily mode' [PR](https://github.com/lynchjames/obsidian-day-planner/pull/179) to add a pomodoro timer to the plugin. I think this is a good idea so this issue is for that work. 

## Visual comps

![image](https://user-images.githubusercontent.com/812139/221322589-54995e38-63ce-4b2c-8ef7-2136be7a9d6a.png)

![image](https://user-images.githubusercontent.com/812139/221322602-6730b9b0-63cb-417e-b37b-e3e80d865822.png)

# TODO
- [ ] Brainstorm best solution for this (manual timer? sub-task of a block of time? configurable setting?)
- [ ] Design something that makes sense
- [ ] Write UI markup 
- [ ] Write styles
- [ ] Create behaviours
- [ ] Add setting to plugin options
