### ISSUE TITLE
Rename plugin and submit to Obsidian Community Plugins

### ISSUE THREAD

**Issue by replete** [replete/obsidian-day-planner#3]
I've added the features I want, once the other issues are done, people would probably the upgrade.

I'm probably not going to develop any file-based features because I'm only interested in it in Daily Mode, but I'll accept PRs for other features.

# TODO:
- [ ] Complete style refresh Feature 
    - [ ] Add break/end styles
- [ ] Complete pomodoro timer Feature
- [ ] Update README.md
    - [ ]  Remove fork blockquote
    - [ ] Add details of new features to README
        - [ ] Daily Mode
        - [ ] Sort items by time
        - [ ] Start / End times
    - [ ] Contextualize updated version paragraph
    - [ ] Add screenshots for new styles
- [ ] Test on Windows
- [ ] Read up on plugin submission requirements
- [ ] Decide on altered plugin name (Day Planner+ probably)
- [ ] Rename repo
- [ ] Update name in `manifest.json`
- [ ] Make release
- [ ] Ask people in Obsidian Discord if they want to test it before submitting to Community Plugins
- [ ] Submit to Obsidian Community Plugins

**Comment by pjkaufman** [comment]
Is this still a work in progress? I am curious since I wanted to see if the plan was to keep this maintained or just for personal use.

**Comment by replete** [comment]
> Is this still a work in progress? I am curious since I wanted to see if the plan was to keep this maintained or just for personal use.

Progress has stalled for now, but I will get to it at some point. It's a service release more than anything, so probably not going to add a load of feature requests, in fact I'll probably trim the functionality down

**Comment by FEI352** [comment]
可惜，我还以为会重新在插件市场上架。
